<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>communitysplinetools.unittest</AssemblyName>
		<PackageId>communitysplinetools.unittest</PackageId>
		<LangVersion>14</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX</DefineConstants>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<OutputPath>../../../../../SandboxRepo/sbox-public/game/.vs/output/</OutputPath>
		<DocumentationFile>../../../../../SandboxRepo/sbox-public/game/.vs/output/communitysplinetools.unittest.xml</DocumentationFile>
		<RootNamespace>Sandbox</RootNamespace>
		<Nullable>disable</Nullable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" /> 
		<PackageReference Include="MSTest.TestAdapter" Version="3.1.1" /> 
		<PackageReference Include="MSTest.TestFramework" Version="3.1.1" /> 
		<PackageReference Include="coverlet.collector" Version="6.0.0" /> 
	</ItemGroup>

	<ItemGroup>
		<Using Include="Sandbox.Internal.GlobalToolsNamespace" Static="true" />
		<Using Include="Sandbox.Internal.GlobalGameNamespace" Static="true" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.CodeUpgrader.dll"/> 
		<Analyzer Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.Generator.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.System.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.Engine.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.Filesystem.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.Reflection.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.Mounting.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Microsoft.AspNetCore.Components.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.AppSystem.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.Tools.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.Compiling.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Microsoft.CodeAnalysis.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Microsoft.CodeAnalysis.CSharp.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Sandbox.Bind.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/Facepunch.ActionGraphs.dll"/> 
		<Reference Include="../../../../../SandboxRepo/sbox-public/game/bin/managed/SkiaSharp.dll"/> 
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../../../../SandboxRepo/sbox-public/game/editor/ActionGraph/Code/actiongraph.csproj" />
		<ProjectReference Include="../Code/communitysplinetools.csproj" />
		<ProjectReference Include="../Editor/communitysplinetools.editor.csproj" />
		<ProjectReference Include="../../../../../SandboxRepo/sbox-public/game/editor/DooEditor/Code/dooeditor.csproj" />
		<ProjectReference Include="../../../../../SandboxRepo/sbox-public/game/editor/Hammer/Code/hammer.csproj" />
		<ProjectReference Include="../../../../../SandboxRepo/sbox-public/game/addons/tools/Code/Base Editor Library.csproj" />
		<ProjectReference Include="../../../../../SandboxRepo/sbox-public/game/editor/MovieMaker/Code/moviemaker.csproj" />
		<ProjectReference Include="../../../../../SandboxRepo/sbox-public/game/editor/ShaderGraph/Code/shadergraph.csproj" />
	</ItemGroup>

</Project>
